version: "3.9"

x-airflow-common: &airflow-common
  image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.10.2-python3.11}
  env_file:
    - .env
  volumes:
    - ./dags:/opt/airflow/dags
    - ./requirements.txt:/requirements.txt
    - ./.env:/opt/airflow/.env
  depends_on:
    - postgres
    - minio

services:
  postgres:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "pip install -r /requirements.txt &&
               airflow db init &&
               airflow users create --username airflow --password airflow --firstname Admin --lastname User --role Admin --email admin@example.com"

volumes:
  postgres_data:
  minio_data:
